name: CFN Nag

on:
  workflow_dispatch:
  push:
    paths:
    - "deploy/pivot_role/pivotRole.yaml"
    branches:
    - main
  pull_request:
    # paths:
    # - "deploy/pivot_role/pivotRole.yaml"
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stelligent/cfn_nag@master
        with:
          input_path: deploy/pivot_role
          extra_args: --ignore-fatal
      - name: Fail if cfn_nag scan contains failures
        run: |
              exit `grep Failures cfn_nag.out | awk '{ SUM += $3} END { print SUM }'`